### ISSUE TITLE
Button Deprecations Messages when compiling

### ISSUE THREAD

**Issue by ack3rs** [mojbro/gocoa#16]
Fix for the Button Deprecations Messages when compiling,  Can you add me as a contributor I have a PR for you. 

<img width="1563" alt="Screenshot 2021-09-10 at 22 45 02" src="https://user-images.githubusercontent.com/3899682/132920956-4899cc64-0e7f-417b-8a26-07106ed233d8.png">

**Comment by mojbro** [comment]
Thanks @acky666! I have merged your PR. I’m happy to see so much activity in this almost abandoned project again. I think I’m going to start reviewing PRs (and actually testing then) just to ensure the project is going the right direction and make sure to mention all contributors in the README. Anyway big thanks for your contribution.
